In [1]:
import pandas as pd
pd.set_option('display.max_rows', 5)
print("Setup complete.")

Setup complete.

In [2]:
fruits = pd.DataFrame({'Apple': [30], 'Bananas': [21]})
fruits

   Apple  Bananas
0     30       21

In [3]:
fruits_sales = pd.DataFrame({
    "Apples": [35, 41],
    "Bananas": [21, 34]
}, index=["2017 Sales", "2018 Sales"])
fruits_sales

            Apples  Bananas
2017 Sales      35       21
2018 Sales      41       34

In [4]:
# crate a variagle ingredients with a series
ingredients = pd.Series(["4 cups", "1 cup", "2 large", "1 can"],
index=["Flour", "Milk", "Eggs", "Spam"],
name="Dinner")
ingredients

Flour     4 cups
Milk       1 cup
Eggs     2 large
Spam       1 can
Name: Dinner, dtype: str

In [5]:
# reviews = pd.read_csv("../input/wine-reviews/winemag-data_first150k.csv", index_col=0)

In [6]:
animals = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])
animals

        Cows  Goats
Year 1    12     22
Year 2    20     19

In [7]:
animals.to_csv("../../outputs/cows_and_goats.csv")

In [8]:
customers = pd.read_csv("../../data/customers.csv", index_col=0)

customers.head()

               name   age region membership
customer_id
C001          佐藤 花子  58.0    名古屋       シルバー
C002          鈴木 一郎  48.0     札幌      レギュラー
C003          高橋 美咲  34.0     大阪      レギュラー
C004          田中 健太   NaN     福岡      レギュラー
C005         伊藤 さくら  27.0     大阪      レギュラー

In [9]:
orders = pd.read_csv("../../data/orders.csv", index_col=0)
orders.head()

,order_date,customer_id,product,category,unit_price,quantity,payment_method
order_id,,,,,,,
1001,2026-04-01,C007,ビジネス書,書籍,1600,3.0,銀行振込
1002,2026-04-02,C002,コーヒー豆,食品,1800,1.0,電子マネー
1003,2026-04-07,C012,マウス,家電,2500,3.0,電子マネー
1004,2026-04-09,C001,ビジネス書,書籍,1600,1.0,電子マネー
1005,2026-04-09,C014,マウス,家電,2500,3.0,クレジットカード

In [10]:
remean_age = customers.age - customers.age.mean()

In [11]:
def stars(row):
    if row.age >= 50:
        return 3
    elif row.age >= 30:
        return 2
    else:
        return 1

star_ratings = customers.apply(stars, axis="columns")

In [12]:
orders.groupby("category").category.count()
orders.groupby("category").unit_price.min()

category
家電    2500
書籍     880
食品     650
Name: unit_price, dtype: int64

In [13]:
orders.groupby("category").unit_price.min()

category
家電    2500
書籍     880
食品     650
Name: unit_price, dtype: int64

In [14]:
orders.groupby("product").apply(lambda df: df.payment_method.iloc[0])

product
キーボード    クレジットカード
コーヒー豆       電子マネー
           ...
技術書      クレジットカード
紅茶       クレジットカード
Length: 9, dtype: str

In [15]:
orders.groupby(["customer_id", "product"]).apply(
    lambda df: df.loc[df.unit_price.idxmax()]
)

                     order_date category  unit_price  quantity payment_method
customer_id product
C001        チョコレート   2026-08-04       食品         650       1.0             現金
            ビジネス書    2026-04-09       書籍        1600       1.0          電子マネー
...                         ...      ...         ...       ...            ...
C014        紅茶       2026-04-21       食品        1200       2.0       クレジットカード
C015        コーヒー豆    2026-07-12       食品        1800       1.0          電子マネー

[45 rows x 5 columns]

In [16]:
orders["total_price"] = orders["quantity"] * orders["unit_price"]

In [17]:
orders

,order_date,customer_id,product,category,unit_price,quantity,payment_method,total_price
order_id,,,,,,,,
1001,2026-04-01,C007,ビジネス書,書籍,1600,3.0,銀行振込,4800.0
1002,2026-04-02,C002,コーヒー豆,食品,1800,1.0,電子マネー,1800.0
...,...,...,...,...,...,...,...,...
1059,2026-09-20,C014,マウス,家電,2500,2.0,銀行振込,5000.0
1060,2026-09-28,C002,コーヒー豆,食品,1800,1.0,電子マネー,1800.0

In [18]:
orders.groupby(["customer_id"]).total_price.agg(["min", "max", "mean"])

                min      max    mean
customer_id
C001          650.0  12500.0  4287.5
C002         1800.0   7500.0  4140.0
...             ...      ...     ...
C014         2400.0   7500.0  4760.0
C015         1800.0   1800.0  1800.0

[14 rows x 3 columns]

In [19]:
orders.sort_values(by="total_price", ascending=False).head(10)

,order_date,customer_id,product,category,unit_price,quantity,payment_method,total_price
order_id,,,,,,,,
1036,2026-07-13,C012,ノートPC,家電,98000,2.0,クレジットカード,196000.0
1055,2026-09-14,C009,ノートPC,家電,98000,1.0,クレジットカード,98000.0
...,...,...,...,...,...,...,...,...
1050,2026-08-15,C012,キーボード,家電,6800,2.0,電子マネー,13600.0
1031,2026-07-05,C013,キーボード,家電,6800,2.0,クレジットカード,13600.0

In [20]:
orders.sort_index().head(10)

,order_date,customer_id,product,category,unit_price,quantity,payment_method,total_price
order_id,,,,,,,,
1001,2026-04-01,C007,ビジネス書,書籍,1600,3.0,銀行振込,4800.0
1002,2026-04-02,C002,コーヒー豆,食品,1800,1.0,電子マネー,1800.0
...,...,...,...,...,...,...,...,...
1009,2026-04-20,C008,コーヒー豆,食品,1800,5.0,クレジットカード,9000.0
1010,2026-04-21,C009,ビジネス書,書籍,1600,3.0,NaN,4800.0

In [21]:
orders.groupby(["customer_id"]).size()

customer_id
C001    4
C002    5
       ..
C014    6
C015    1
Length: 14, dtype: int64

In [22]:
# dtype
customers = pd.read_csv("../../data/customers.csv")
customers.dtypes

customer_id        str
name               str
age            float64
region             str
membership         str
dtype: object

In [23]:
orders = pd.read_csv("../../data/orders.csv")
orders.dtypes

order_id            int64
order_date            str
                   ...
quantity          float64
payment_method        str
Length: 8, dtype: object

In [24]:
orders.index.dtype

dtype('int64')

In [25]:
orders.payment_method.isna

<bound method Series.isna of 0      銀行振込
1     電子マネー
      ...
58     銀行振込
59    電子マネー
Name: payment_method, Length: 60, dtype: str>

In [26]:
orders.payment_method.isna().sum()

np.int64(3)

In [27]:
orders_fillna = orders.payment_method.fillna("cash")
orders_fillna.iloc[8:12]

8     クレジットカード
9         cash
10    クレジットカード
11    クレジットカード
Name: payment_method, dtype: str

In [28]:
orders.iloc[8:12]

,order_id,order_date,customer_id,product,category,unit_price,quantity,payment_method
8,1009,2026-04-20,C008,コーヒー豆,食品,1800,5.0,クレジットカード
9,1010,2026-04-21,C009,ビジネス書,書籍,1600,3.0,NaN
10,1011,2026-04-21,C014,紅茶,食品,1200,2.0,クレジットカード
11,1012,2026-04-21,C014,技術書,書籍,3200,2.0,クレジットカード

In [29]:
orders.payment_method.isna()

0     False
1     False
      ...
58    False
59    False
Name: payment_method, Length: 60, dtype: bool

In [30]:
orders.rename(index={0: "first", 1: "second"})

,order_id,order_date,customer_id,product,category,unit_price,quantity,payment_method
first,1001,2026-04-01,C007,ビジネス書,書籍,1600,3.0,銀行振込
second,1002,2026-04-02,C002,コーヒー豆,食品,1800,1.0,電子マネー
...,...,...,...,...,...,...,...,...
58,1059,2026-09-20,C014,マウス,家電,2500,2.0,銀行振込
59,1060,2026-09-28,C002,コーヒー豆,食品,1800,1.0,電子マネー

In [31]:
orders.rename_axis("orders", axis="rows").rename_axis("fields", axis="columns")

fields,order_id,order_date,customer_id,product,category,unit_price,quantity,payment_method
orders,,,,,,,,
0,1001,2026-04-01,C007,ビジネス書,書籍,1600,3.0,銀行振込
1,1002,2026-04-02,C002,コーヒー豆,食品,1800,1.0,電子マネー
...,...,...,...,...,...,...,...,...
58,1059,2026-09-20,C014,マウス,家電,2500,2.0,銀行振込
59,1060,2026-09-28,C002,コーヒー豆,食品,1800,1.0,電子マネー